### ISSUE TITLE
Android: crash after login

### ISSUE THREAD

**Issue by blavenie** [duniter/cesium#346]
```
02-17 10:30:45.935 15578-15763/fr.duniter.cesium D/MiniSodium: execute action: crypto_box_open_easy
                                                               
                                                               --------- beginning of crash
02-17 10:30:45.937 15578-15607/fr.duniter.cesium E/AndroidRuntime: FATAL EXCEPTION: pool-1-thread-1
                                                                   Process: fr.duniter.cesium, PID: 15578
                                                                   java.lang.NegativeArraySizeException: -15
                                                                       at me.lockate.plugins.MiniSodium$19.run(MiniSodium.java:633)
                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                       at java.lang.Thread.run(Thread.java:818)
```

**Comment by blavenie** [comment]
Ceci est lié à ce code Java (MiniSodium.java) : 
```java
cordova.getThreadPool().execute(new Runnable(){
				public void run(){
					int mlen = clen - libsodium.crypto_box_macbytes();  // ICI: clen est inférieur a macbytes
					byte[] m = new byte[mlen];  // Crash car mlen < 0

```
