### ISSUE TITLE
Error "p.secure.set is not a function"

### ISSUE THREAD

**Issue by blavenie** [duniter/cesium#471]
After login, user get this error : 
```
p.secure.set is not a function
```

**Comment by blavenie** [comment]
This append when a lock screen has been enable (due to secure storage plugin).
Get this error in debug mode : 
```
06-06 08:59:54.396 10242-10242/fr.duniter.cesium I/chromium: [INFO:CONSOLE(26794)] "TypeError: exports.secure.set is not a function
                                                                 at Object.exports.secure.setObject (file:///android_asset/www/dist/dist_js/app/services/storage-services.js:83:29)
                                                                 at store (file:///android_asset/www/dist/dist_js/app/services/wallet-services.js:292:24)
                                                                 at file:///android_asset/www/dist/dist_js/app/services/wallet-services.js:220:13
                                                                 at processQueue (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:29127:28)
                                                                 at file:///android_asset/www/lib/ionic/js/ionic.bundle.js:29143:27
                                                                 at Scope.$eval (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:30395:28)
                                                                 at Scope.$digest (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:30211:31)
                                                                 at file:///android_asset/www/lib/ionic/js/ionic.bundle.js:30434:26
                                                                 at completeOutstandingRequest (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:19194:10)
                                                                 at file:///android_asset/www/lib/ionic/js/ionic.bundle.js:19470:7", source: file:///android_asset/www/lib/ionic/js/ionic.bundle.js (26794)
```
